services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  wp:
    image: wordpress:php8.2-apache
    container_name: wp_app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "${WP_PORT}:80"     # Visit http://localhost:${WP_PORT}
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WP_HOME: ${WP_HOME}          # optional but nice for parity
      WP_SITEURL: ${WP_SITEURL}    # optional but nice for parity

    volumes:
      - wp_html:/var/www/html
      - ./wp-content/themes/your-child-theme:/var/www/html/wp-content/themes/your-child-theme
      - ./wp-content/plugins/your-custom-plugin:/var/www/html/wp-content/plugins/your-custom-plugin
